export const flatTree = [
  {
    revision_uid: "soGE5YItB3vBiA",
    bomline_uid: "root",
    name: "Research Vessel 53 meters",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456611",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "root",
    quantity: -1,
    ico_class_name: "96X01 - Ship",
    ico_class_id: "96X01",
    bomline_level: 0,
    sequence_number: 0,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "RaHEvEz_B3vBiA",
    bomline_uid: "g3ME5ch9B3vBiA",
    name: "96X08 - Auxiliary Systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456658",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "soGE5YItB3vBiA",
    quantity: -1,
    ico_class_name: "96X08 - Auxiliary Systems",
    ico_class_id: "96X08",
    bomline_level: 1,
    sequence_number: null,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "StJEvAukB3vBiA",
    bomline_uid: "h5GE5cU4B3vBiA",
    name: "96X12 - Tools and Spare parts",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456782",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "soGE5YItB3vBiA",
    quantity: -1,
    ico_class_name: "96X12 - Tools and Spare parts",
    ico_class_id: "96X12",
    bomline_level: 1,
    sequence_number: null,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "4ZJE$FKwB3vBiA",
    bomline_uid: "idNEvAukB3vBiA",
    name: "0Y02 - Tools (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB181323",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "igIEvAukB3vBiA",
    quantity: -1,
    ico_class_name: "0Y02 - Tools (engine)",
    ico_class_id: "0Y02",
    bomline_level: 3,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "EuBE$EhfB3vBiA",
    bomline_uid: "RTJE5cU4B3vBiA",
    name: "0Y02 - Tools (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456787",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "xmDE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "0Y02 - Tools (engine)",
    ico_class_id: "0Y02",
    bomline_level: 3,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "FwGE$EhfB3vBiA",
    bomline_uid: "ysME5cU4B3vBiA",
    name: "0Y04 - Spare parts (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456790",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "iEOE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "0Y04 - Spare parts (engine)",
    ico_class_id: "0Y04",
    bomline_level: 3,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "AXLE5cU4B3vBiA",
    bomline_uid: "RiHEvEz_B3vBiA",
    name: "11X01 - NOx emission control systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456771",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "11X01 - NOx emission control systems",
    ico_class_id: "11X01",
    bomline_level: 2,
    sequence_number: 110,
    release_status: "Wb9_AsSold",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "wjHE5ch9B3vBiA",
    bomline_uid: "ReOEvEz_B3vBiA",
    name: "1X01 - Fuel oil systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456659",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "1X01 - Fuel oil systems",
    ico_class_id: "1X01",
    bomline_level: 2,
    sequence_number: 10,
    release_status: "Wb9_AsSold",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "iVKEfIhiB3vBiA",
    bomline_uid: "RiBEvEz_B3vBiA",
    name: "3X01 - Compressed air systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456675",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "3X01 - Compressed air systems",
    ico_class_id: "3X01",
    bomline_level: 2,
    sequence_number: 30,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "iFKEvEuzB3vBiA",
    bomline_uid: "RiCEvEz_B3vBiA",
    name: "4X01 - Cooling water systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456691",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "4X01 - Cooling water systems",
    ico_class_id: "4X01",
    bomline_level: 2,
    sequence_number: 40,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "mHJE5ch9B3vBiA",
    bomline_uid: "RiDEvEz_B3vBiA",
    name: "5X01 - Combustion air and exhaust gas systems",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456706",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "5X01 - Combustion air and exhaust gas systems",
    ico_class_id: "5X01",
    bomline_level: 2,
    sequence_number: 50,
    release_status: "Wb9_AsSold",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "cbKE5ch9B3vBiA",
    bomline_uid: "RiFEvEz_B3vBiA",
    name: "7X01 - Power transmission",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456739",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "7X01 - Power transmission",
    ico_class_id: "7X01",
    bomline_level: 2,
    sequence_number: 70,
    release_status: "Wb9_AsSold",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "hFDEvEz_B3vBiA",
    bomline_uid: "R6JEvEz_B3vBiA",
    name: "XAAB181732",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAB181732",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: -1,
    ico_class_name: "8X01 - Engine control & monitoring",
    ico_class_id: "8X01",
    bomline_level: 2,
    sequence_number: 120,
    release_status: "",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "9bIE5ch9B3vBiA",
    bomline_uid: "RiGEvEz_B3vBiA",
    name: "9X01 - Electric components",
    object_type: "Wb8_LogicalBlockRevision",
    item_id: "XAAA456748",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "RaHEvEz_B3vBiA",
    quantity: 1,
    ico_class_name: "9X01 - Electric components",
    ico_class_id: "9X01",
    bomline_level: 2,
    sequence_number: 90,
    release_status: "Wb9_AsSold",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "4ZJE$FKwB3vBiA",
    bomline_uid: "idNEvAukB3vBiA",
    name: "0Y02 - Tools (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB181323",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "igIEvAukB3vBiA",
    quantity: -1,
    ico_class_name: "0Y02 - Tools (engine)",
    ico_class_id: "0Y02",
    bomline_level: 3,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "EuBE$EhfB3vBiA",
    bomline_uid: "RTJE5cU4B3vBiA",
    name: "0Y02 - Tools (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456787",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "xmDE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "0Y02 - Tools (engine)",
    ico_class_id: "0Y02",
    bomline_level: 3,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "FwGE$EhfB3vBiA",
    bomline_uid: "ysME5cU4B3vBiA",
    name: "0Y04 - Spare parts (engine)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456790",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "iEOE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "0Y04 - Spare parts (engine)",
    ico_class_id: "0Y04",
    bomline_level: 3,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "2hNE$EhfB3vBiA",
    bomline_uid: "BsCE5cU4B3vBiA",
    name: "11N13 - Emission analyzer",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456777",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "QrIE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "11N13 - Emission analyzer",
    ico_class_id: "11N13",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "nQIE$FKwB3vBiA",
    bomline_uid: "ChKE5ch9B3vBiA",
    name: "1E04 - Cooler (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456667",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "RfOE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1E04 - Cooler (MDF)",
    ico_class_id: "1E04",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "XgKE$FKwB3vBiA",
    bomline_uid: "S2FE5ch9B3vBiA",
    name: "1E04 - Cooler (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456674",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "yZHE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1E04 - Cooler (MDF)",
    ico_class_id: "1E04",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "TGFIiNxyytomSA",
    bomline_uid: "yBME5ch9B3vBiA",
    name: "1F07 - Suction strainer (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456670",
    item_revision_id: "G",
    description: null,
    parent_revision_uid: "C5FE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1F07 - Suction strainer (MDF)",
    ico_class_id: "1F07",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "V_KE$FKwB3vBiA",
    bomline_uid: "BCEE5ch9B3vBiA",
    name: "1F07 - Suction strainer (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456663",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "xEFE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1F07 - Suction strainer (MDF)",
    ico_class_id: "1F07",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ZzLE$AdTB3vBiA",
    bomline_uid: "FVEE5ch9B3vBiA",
    name: "3F02 - Air filter (starting air inlet)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456686",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "lQJE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3F02 - Air filter (starting air inlet)",
    ico_class_id: "3F02",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "agHE$AdTB3vBiA",
    bomline_uid: "V4OE5ch9B3vBiA",
    name: "3F02 - Air filter (starting air inlet)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456683",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "EJIE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3F02 - Air filter (starting air inlet)",
    ico_class_id: "3F02",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "oCHE$AdTB3vBiA",
    bomline_uid: "yJBEfIhiB3vBiA",
    name: "XAAA235916",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB170803",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RxLEfIhiB3vBiA",
    quantity: -1,
    ico_class_name: "3N03 - Pressure reduction unit",
    ico_class_id: "3N03",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "YeHE$AdTB3vBiA",
    bomline_uid: "yBPEfIhiB3vBiA",
    name: "XAAA235916",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB170802",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RpOEfIhiB3vBiA",
    quantity: -1,
    ico_class_name: "3N03 - Pressure reduction unit",
    ico_class_id: "3N03",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "l_BE$EhfB3vBiA",
    bomline_uid: "lxLE5ch9B3vBiA",
    name: "3T01 - Starting air vessel",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456690",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "FpPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3T01 - Starting air vessel",
    ico_class_id: "3T01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: "Yard No 065 article no 1",
    customer_tag: null
  },
  {
    revision_uid: "lGGE$EhfB3vBiA",
    bomline_uid: "DeAE5ch9B3vBiA",
    name: "3T01 - Starting air vessel",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456680",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "DQPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3T01 - Starting air vessel",
    ico_class_id: "3T01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: "Yard No 065 article no 1",
    customer_tag: null
  },
  {
    revision_uid: "MoIE$AdTB3vBiA",
    bomline_uid: "m6GE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456702",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "G2LE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "4E08 - Central cooler",
    ico_class_id: "4E08",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "LPOE$AdTB3vBiA",
    bomline_uid: "GiAE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456698",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "WNPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "4E08 - Central cooler",
    ico_class_id: "4E08",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "RfKE$FKxB3vBiA",
    bomline_uid: "xvPE$FKxB3vBiA",
    name: "4V02 - Temperature control valve (heat recovery)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB227621",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "wbEE$FKxB3vBiA",
    quantity: -1,
    ico_class_name: "4V02 - Temperature control valve (heat recovery)",
    ico_class_id: "4V02",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ymDE$FKwB3vBiA",
    bomline_uid: "ixKEvEuzB3vBiA",
    name: "5394-7",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB184371",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "igCEvEuzB3vBiA",
    quantity: -1,
    ico_class_name: "4V08 - Temperature control valve (central cooler)",
    ico_class_id: "4V08",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "NePE$AdTB3vBiA",
    bomline_uid: "7UEE5ch9B3vBiA",
    name: "5H01 - Exhaust gas bellows",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456726",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "bQGE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5H01 - Exhaust gas bellows",
    ico_class_id: "5H01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "dOJE$AdTB3vBiA",
    bomline_uid: "JmLE5ch9B3vBiA",
    name: "5H01 - Exhaust gas bellows",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456714",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "Y3KE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5H01 - Exhaust gas bellows",
    ico_class_id: "5H01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "_wGE$AdTB3vBiA",
    bomline_uid: "bhNE5ch9B3vBiA",
    name: "5Z01 - Connection piece",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456730",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "7oPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z01 - Connection piece",
    ico_class_id: "5Z01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "9fKE$AdTB3vBiA",
    bomline_uid: "qbPE5ch9B3vBiA",
    name: "5Z01 - Connection piece",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456720",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "6dAE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z01 - Connection piece",
    ico_class_id: "5Z01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "i5JE$EhfB3vBiA",
    bomline_uid: "3fIE5ch9B3vBiA",
    name: "5Z03 - Turbocharger cleaning device",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456710",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "XpPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z03 - Turbocharger cleaning device",
    ico_class_id: "5Z03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "H_KEd6zQB3vBiA",
    bomline_uid: "X_NEd6zQB3vBiA",
    name: "XAAA788606",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA912402",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "X_AEd6zQB3vBiA",
    quantity: 1,
    ico_class_name: "7C01 - Flexible coupling (flywheel)",
    ico_class_id: "7C01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: "for PAAE338395",
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "LPFEd6zQB3vBiA",
    bomline_uid: "bHAEd6zQB3vBiA",
    name: "XAAA788606",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA912422",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "bDJEd6zQB3vBiA",
    quantity: 1,
    ico_class_name: "7C01 - Flexible coupling (flywheel)",
    ico_class_id: "7C01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: "for PAAE338396",
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "fWPE$AdTB3vBiA",
    bomline_uid: "hCNEvEz_B3vBiA",
    name: "8N39 - Ethernet connection box",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB181734",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RtIEvEz_B3vBiA",
    quantity: -1,
    ico_class_name: "8N39 - Ethernet connection box",
    ico_class_id: "8N39",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "AyIE$EhfB3vBiA",
    bomline_uid: "fbBE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456756",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "PiIE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "9N03 - Motor starter pre-lube oil pump",
    ico_class_id: "9N03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ABKE$EhfB3vBiA",
    bomline_uid: "QWLE5cU4B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456766",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "wdGE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "9N03 - Motor starter pre-lube oil pump",
    ico_class_id: "9N03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "hdNE$EhfB3vBiA",
    bomline_uid: "wyKE5cU4B3vBiA",
    name: "9N36 - Power unit",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456770",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "QuIE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "9N36 - Power Unit",
    ico_class_id: "9N36",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "RZOE$EhfB3vBiA",
    bomline_uid: "fpKE5ch9B3vBiA",
    name: "9N36 - Power unit",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456753",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "uGKE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "9N36 - Power Unit",
    ico_class_id: "9N36",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "2hNE$EhfB3vBiA",
    bomline_uid: "BsCE5cU4B3vBiA",
    name: "11N13 - Emission analyzer",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456777",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "QrIE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "11N13 - Emission analyzer",
    ico_class_id: "11N13",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "nQIE$FKwB3vBiA",
    bomline_uid: "ChKE5ch9B3vBiA",
    name: "1E04 - Cooler (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456667",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "RfOE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1E04 - Cooler (MDF)",
    ico_class_id: "1E04",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "XgKE$FKwB3vBiA",
    bomline_uid: "S2FE5ch9B3vBiA",
    name: "1E04 - Cooler (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456674",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "yZHE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1E04 - Cooler (MDF)",
    ico_class_id: "1E04",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "TGFIiNxyytomSA",
    bomline_uid: "yBME5ch9B3vBiA",
    name: "1F07 - Suction strainer (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456670",
    item_revision_id: "G",
    description: null,
    parent_revision_uid: "C5FE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1F07 - Suction strainer (MDF)",
    ico_class_id: "1F07",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "V_KE$FKwB3vBiA",
    bomline_uid: "BCEE5ch9B3vBiA",
    name: "1F07 - Suction strainer (MDF)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456663",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "xEFE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "1F07 - Suction strainer (MDF)",
    ico_class_id: "1F07",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ZzLE$AdTB3vBiA",
    bomline_uid: "FVEE5ch9B3vBiA",
    name: "3F02 - Air filter (starting air inlet)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456686",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "lQJE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3F02 - Air filter (starting air inlet)",
    ico_class_id: "3F02",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "agHE$AdTB3vBiA",
    bomline_uid: "V4OE5ch9B3vBiA",
    name: "3F02 - Air filter (starting air inlet)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456683",
    item_revision_id: "D",
    description: null,
    parent_revision_uid: "EJIE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3F02 - Air filter (starting air inlet)",
    ico_class_id: "3F02",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "oCHE$AdTB3vBiA",
    bomline_uid: "yJBEfIhiB3vBiA",
    name: "XAAA235916",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB170803",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RxLEfIhiB3vBiA",
    quantity: -1,
    ico_class_name: "3N03 - Pressure reduction unit",
    ico_class_id: "3N03",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "YeHE$AdTB3vBiA",
    bomline_uid: "yBPEfIhiB3vBiA",
    name: "XAAA235916",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB170802",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RpOEfIhiB3vBiA",
    quantity: -1,
    ico_class_name: "3N03 - Pressure reduction unit",
    ico_class_id: "3N03",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "l_BE$EhfB3vBiA",
    bomline_uid: "lxLE5ch9B3vBiA",
    name: "3T01 - Starting air vessel",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456690",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "FpPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3T01 - Starting air vessel",
    ico_class_id: "3T01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: "Yard No 065 article no 1",
    customer_tag: null
  },
  {
    revision_uid: "lGGE$EhfB3vBiA",
    bomline_uid: "DeAE5ch9B3vBiA",
    name: "3T01 - Starting air vessel",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456680",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "DQPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "3T01 - Starting air vessel",
    ico_class_id: "3T01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: "Yard No 065 article no 1",
    customer_tag: null
  },
  {
    revision_uid: "MoIE$AdTB3vBiA",
    bomline_uid: "m6GE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456702",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "G2LE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "4E08 - Central cooler",
    ico_class_id: "4E08",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "LPOE$AdTB3vBiA",
    bomline_uid: "GiAE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456698",
    item_revision_id: "C",
    description: null,
    parent_revision_uid: "WNPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "4E08 - Central cooler",
    ico_class_id: "4E08",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "RfKE$FKxB3vBiA",
    bomline_uid: "xvPE$FKxB3vBiA",
    name: "4V02 - Temperature control valve (heat recovery)",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB227621",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "wbEE$FKxB3vBiA",
    quantity: -1,
    ico_class_name: "4V02 - Temperature control valve (heat recovery)",
    ico_class_id: "4V02",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ymDE$FKwB3vBiA",
    bomline_uid: "ixKEvEuzB3vBiA",
    name: "5394-7",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB184371",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "igCEvEuzB3vBiA",
    quantity: -1,
    ico_class_name: "4V08 - Temperature control valve (central cooler)",
    ico_class_id: "4V08",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "NePE$AdTB3vBiA",
    bomline_uid: "7UEE5ch9B3vBiA",
    name: "5H01 - Exhaust gas bellows",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456726",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "bQGE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5H01 - Exhaust gas bellows",
    ico_class_id: "5H01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "dOJE$AdTB3vBiA",
    bomline_uid: "JmLE5ch9B3vBiA",
    name: "5H01 - Exhaust gas bellows",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456714",
    item_revision_id: "B",
    description: null,
    parent_revision_uid: "Y3KE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5H01 - Exhaust gas bellows",
    ico_class_id: "5H01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "_wGE$AdTB3vBiA",
    bomline_uid: "bhNE5ch9B3vBiA",
    name: "5Z01 - Connection piece",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456730",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "7oPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z01 - Connection piece",
    ico_class_id: "5Z01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "9fKE$AdTB3vBiA",
    bomline_uid: "qbPE5ch9B3vBiA",
    name: "5Z01 - Connection piece",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456720",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "6dAE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z01 - Connection piece",
    ico_class_id: "5Z01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "i5JE$EhfB3vBiA",
    bomline_uid: "3fIE5ch9B3vBiA",
    name: "5Z03 - Turbocharger cleaning device",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456710",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "XpPE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "5Z03 - Turbocharger cleaning device",
    ico_class_id: "5Z03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "H_KEd6zQB3vBiA",
    bomline_uid: "X_NEd6zQB3vBiA",
    name: "XAAA788606",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA912402",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "X_AEd6zQB3vBiA",
    quantity: 1,
    ico_class_name: "7C01 - Flexible coupling (flywheel)",
    ico_class_id: "7C01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: "for PAAE338395",
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "LPFEd6zQB3vBiA",
    bomline_uid: "bHAEd6zQB3vBiA",
    name: "XAAA788606",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA912422",
    item_revision_id: "-",
    description: null,
    parent_revision_uid: "bDJEd6zQB3vBiA",
    quantity: 1,
    ico_class_name: "7C01 - Flexible coupling (flywheel)",
    ico_class_id: "7C01",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: "for PAAE338396",
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "fWPE$AdTB3vBiA",
    bomline_uid: "hCNEvEz_B3vBiA",
    name: "8N39 - Ethernet connection box",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAB181734",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "RtIEvEz_B3vBiA",
    quantity: -1,
    ico_class_name: "8N39 - Ethernet connection box",
    ico_class_id: "8N39",
    bomline_level: 4,
    sequence_number: 10,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "AyIE$EhfB3vBiA",
    bomline_uid: "fbBE5ch9B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456756",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "PiIE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "9N03 - Motor starter pre-lube oil pump",
    ico_class_id: "9N03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "ABKE$EhfB3vBiA",
    bomline_uid: "QWLE5cU4B3vBiA",
    name: "-",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456766",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "wdGE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "9N03 - Motor starter pre-lube oil pump",
    ico_class_id: "9N03",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "hdNE$EhfB3vBiA",
    bomline_uid: "wyKE5cU4B3vBiA",
    name: "9N36 - Power unit",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456770",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "QuIE5cU4B3vBiA",
    quantity: 1,
    ico_class_name: "9N36 - Power Unit",
    ico_class_id: "9N36",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  },
  {
    revision_uid: "RZOE$EhfB3vBiA",
    bomline_uid: "fpKE5ch9B3vBiA",
    name: "9N36 - Power unit",
    object_type: "Wb8_SolutionItemRevision",
    item_id: "XAAA456753",
    item_revision_id: "A",
    description: null,
    parent_revision_uid: "uGKE5ch9B3vBiA",
    quantity: 1,
    ico_class_name: "9N36 - Power Unit",
    ico_class_id: "9N36",
    bomline_level: 4,
    sequence_number: 1,
    release_status: "Approved, Sent to SAP, Wb8_PORReleased",
    wartsila_tag: null,
    yard_tag: null,
    customer_tag: null
  }
];
